name: CI-Train and Save model

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  matrix-pip:
    name: Train and Save model
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.11,3.12]
    steps:
      -name: Checkout
       uses: actions/checkout@v4

      -name: Set up Python ${{ matrix.python }}
       uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      -name: Upgrade pip
       run: python -m pip install --upgrade pip setuptools wheel

      -name: Install dependencies
       run: pip install -r requirements.txt

      -name: Train the model
       run: |
          python train.py
          ls -la artifacts

      -name: upload artifacts
       uses: actions/upload-artifact@v3
        with:
          name: ml-artifacts-${{ matrix.python }}-${{ github.run_id }}
          path: artifacts


